export type Product = {
  id: number
  name: string
  price: number
  description: string
  image: string
  category: number // 1: Retro corta, 2: Retro larga, 3: Actual
  categoryName: string
  brand: string
  stock: number
  videoUrl: string
}

export const products: Product[] = [
  // Categoría 1: Retro corta
  {
    id: 1,
    name: "Camiseta Colo-Colo 1991",
    price: 29990,
    description: "Camiseta retro de Colo-Colo temporada 1991, edición especial conmemorativa de la Copa Libertadores.",
    image: "/img/img-retro-corta/coloclo-1991.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 25,
    videoUrl: "https://www.youtube.com/watch?v=VSWBpiHFrtU",
    
  },
  {
    id: 2,
    name: "Camiseta Universidad de Chile 1998",
    price: 29990,
    description: "Camiseta retro de Universidad de Chile temporada 1998, diseño clásico con el tradicional azul.",
    image: "/img/img-retro-corta/uchile-1998.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 18,
    videoUrl: "",
  },
  {
    id: 3,
    name: "Camiseta Universidad Católica Retro",
    price: 29990,
    description: "Camiseta retro de Universidad Católica, diseño clásico con la franja cruzada.",
    image: "/img/img-retro-corta/ucatolica-retro1.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 22,
    videoUrl: "",
  },
  {
    id: 4,
    name: "Camiseta Universidad de Chile 2011",
    price: 29990,
    description: "Camiseta conmemorativa de Universidad de Chile temporada 2011, año de la Copa Sudamericana.",
    image: "/img/img-retro-corta/uchile-2011.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  },
  {
    id: 5,
    name: "Camiseta Santos FC - Neymar",
    price: 29990,
    description: "Camiseta retro del Santos FC con el número 11 de Neymar Jr., edición especial.",
    image: "/img/img-retro-corta/santos-neymar.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 10,
    videoUrl: "",
  },
  {
    id: 6,
    name: "Camiseta Atlético Madrid Spiderman",
    price: 29990,
    description: "Edición especial de la camiseta del Atlético de Madrid con diseño de Spiderman.",
    image: "/img/img-retro-corta/atleti-spiderman.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 8,
    videoUrl: "",
  },

  // Categoría 2: Retro larga
  {
    id: 7,
    name: "Camiseta Colo-Colo 2006",
    price: 31990,
    description: "Camiseta manga larga de Colo-Colo temporada 2006, diseño clásico del Cacique.",
    image: "/img/img-retro-larga/colocolo-2006.jpeg",
    category: 2,
    categoryName: "Retro larga",
    brand: "CashBak Sports",
    stock: 12,
    videoUrl: "",
  },
  {
    id: 8,
    name: "Camiseta Real Madrid 2017",
    price: 31990,
    description: "Camiseta manga larga del Real Madrid temporada 2017, año de la Champions League.",
    image: "/img/img-retro-larga/real-2017.jpeg",
    category: 2,
    categoryName: "Retro larga",
    brand: "CashBak Sports",
    stock: 9,
    videoUrl: "",
  },
  {
    id: 9,
    name: "Camiseta Manchester United 2008",
    price: 31990,
    description: "Camiseta manga larga del Manchester United temporada 2008, edición conmemorativa de la Champions League.",
    image: "/img/img-retro-larga/united-2008.jpeg",
    category: 2,
    categoryName: "Retro larga",
    brand: "CashBak Sports",
    stock: 7,
    videoUrl: "",
  },

  // Categoría 3: Actual
  {
    id: 10,
    name: "Camiseta Colo-Colo 2025/26",
    price: 24900,
    description:
      "Camiseta oficial de Colo-Colo para la temporada 2025/26, diseño moderno con tecnología de última generación.",
    image: "/img/img-actual/colocolo-25.26.jpeg",
    category: 3,
    categoryName: "Actual",
    brand: "CashBak Sports",
    stock: 30,
    videoUrl: "",
  },
  {
    id: 11,
    name: "Camiseta Colo-Colo Centenario",
    price: 24900,
    description: "Edición especial conmemorativa del centenario de Colo-Colo, diseño exclusivo y numerado.",
    image: "/img/img-actual/colocolo-centenario.jpeg",
    category: 3,
    categoryName: "Actual",
    brand: "CashBak Sports",
    stock: 20,
    videoUrl: "",
  },
  {
    id: 12,
    name: "Camiseta Universidad de Chile 2025/26",
    price: 24900,
    description:
      "Camiseta oficial de Universidad de Chile para la temporada 2025/26, con tecnología de última generación.",
    image: "/img/img-actual/uchile-25-26.jpeg",
    category: 3,
    categoryName: "Actual",
    brand: "CashBak Sports",
    stock: 25,
    videoUrl: "",
  },
  {
    id: 13,
    name: "Camiseta Barcelona 2011",
    price: 29990,
    description: "Camiseta Barcelona primera Champions.",
    image: "/img/img-retro-corta/barca-2008.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  },
  {
    id: 14,
    name: "Camiseta Boca",
    price: 29990,
    description: "Camiseta.",
    image: "/img/img-retro-corta/boca-medel.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  },

  {
    id: 15,
    name: "Camiseta Fiorentina Nintendo",
    price: 29990,
    description: "Camiseta.",
    image: "/img/img-retro-corta/fiorentina-nintendo.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  },

  {
    id: 16,
    name: "Camiseta Juventus 2016",
    price: 29990,
    description: "Camiseta.",
    image: "/img/img-retro-corta/juventus-2016.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  },

  {
    id: 17,
    name: "Camiseta Real Madrid 2009",
    price: 29990,
    description: "Camiseta.",
    image: "/img/img-retro-corta/real-2009.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  },

  {
    id: 18,
    name: "Camiseta River Plate Salas",
    price: 29990,
    description: "Camiseta.",
    image: "/img/img-retro-corta/river-salas.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  },

  {
    id: 19,
    name: "Camiseta U. Católica Retro",
    price: 29990,
    description: "Camiseta.",
    image: "/img/img-retro-corta/ucatolica-retro2.jpeg",
    category: 1,
    categoryName: "Retro corta",
    brand: "CashBak Sports",
    stock: 15,
    videoUrl: "",
  }
]
